language: php

php:
  - 7.3

before_script:
  - cp .env.testing .env
  - mysql -e 'create database test_db;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit
