language: php

php:
  - 7.2

before_script:
  - cp .env.testing .env
  - mysql -e 'create database travis_db;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit -c phpunit_travis.xml

services:
  - mysql

dist: xenial
